# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eba31579693980f47d10eaaf4d16b0aca2701b60ae3162c6f56482f5c9a1e43a43ae28374480a9b9930e34ed248da062905a92c0fa3cd6abf4f483f376e0751

test:
  secret_key_base: d1e17be0b3eb24164692b08bd4e7c9013d30b6e41c0756ad7af5115254cb024e5971f5b4709a59abecdc81a47af564450dbfb408c455945a234e55a19ffb8a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
